<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version Condition="'$(FlatFileMetaIncluded)' != 'True'">0.0.1-beta</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Description>Nacha (ACH) Flat File Parser (Read &amp; Write)</Description>
    <Company>Ekon Benefits</Company>
    <Authors>Jay Tuley</Authors>
    <Copyright>Copyright 2018 Ekon Benefits</Copyright>
    <PackageProjectUrl>https://github.com/ekonbenefits/NachaSharp</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/ekonbenefits/NachaSharp/blob/master/LICENSE</PackageLicenseUrl>
    <PackageTags>nacha banking ach flatfile text data</PackageTags>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <DisableImplicitFSharpCoreReference>True</DisableImplicitFSharpCoreReference>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="NachaValues.fs" />
    <Compile Include="NachaRecords\NachaRecords.fs" />
    <Compile Include="NachaRecords\EntryDetail\EntryAddenda.fs" />
    <Compile Include="NachaRecords\EntryDetail\EntryDetail.fs" />
    <Compile Include="NachaRecords\BatchControlRecord.fs" />
    <Compile Include="NachaRecords\BatchHeaderRecord.fs" />
    <Compile Include="NachaRecords\FileControlRecord.fs" />
    <Compile Include="NachaRecords\FileHeaderRecord.fs" />
    <Compile Include="NachaFile.fs" />
  </ItemGroup>
  <ItemGroup>

    <PackageReference Condition="'$(FlatFileMetaIncluded)' != 'True'" Include="FSharp.Data.FlatFileMeta" Version="*" />
    <ProjectReference Condition="'$(FlatFileMetaIncluded)' == 'True'" Include="../../FSharp.Data.FlatFileMeta/FSharp.Data.FlatFileMeta/FSharp.Data.FlatFileMeta.fsproj" />
  </ItemGroup>

</Project>
